# -------------------------------------------------------
# Storage — state bucket, firmware bucket, Artifact Registry
# -------------------------------------------------------

locals {
  bucket_lifecycle = {
    num_newer_versions = 10
  }
}

# Terraform remote state
resource "google_storage_bucket" "tfstate" {
  name                        = "${var.GCP_PROJECT_ID}-tfstate"
  location                    = "EU"
  force_destroy               = false
  uniform_bucket_level_access = true

  versioning {
    enabled = true
  }

  lifecycle_rule {
    condition {
      num_newer_versions = local.bucket_lifecycle.num_newer_versions
    }
    action {
      type = "Delete"
    }
  }

  lifecycle {
    prevent_destroy = true
  }
}

# OTA firmware — signed URLs generated by litter-firmware-check Cloud Function
resource "google_storage_bucket" "firmware" {
  name                        = "${var.GCP_PROJECT_ID}-firmware"
  location                    = var.GCP_REGION
  force_destroy               = false
  uniform_bucket_level_access = false # signed URL generation requires ACL-based access

  versioning {
    enabled = true
  }

  lifecycle_rule {
    condition {
      num_newer_versions = local.bucket_lifecycle.num_newer_versions
    }
    action {
      type = "Delete"
    }
  }

  lifecycle {
    prevent_destroy = true
  }
}

# Docker registry for Cloud Run API images
resource "google_artifact_registry_repository" "api" {
  location      = var.GCP_REGION
  repository_id = "${var.GCP_PROJECT_ID}-registry-docker"
  format        = "DOCKER"
}

resource "google_artifact_registry_repository_iam_member" "cloudbuild_push" {
  project    = var.GCP_PROJECT_ID
  location   = var.GCP_REGION
  repository = google_artifact_registry_repository.api.name
  role       = "roles/artifactregistry.writer"
  member     = "serviceAccount:${data.google_project.project.number}@cloudbuild.gserviceaccount.com"
}
