name: Terraform Infra

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform:
    uses: Datally-Solutions/cicd/.github/workflows/reusable-terraform.yml@main
    with:
      working_directory: "."
      state_prefix: "infra"
      has_tfvars: "true"
    secrets:
      WIF_PROVIDER_S: ${{ secrets.WIF_PROVIDER }}
      CICD_SA_EMAIL_S: ${{ secrets.CICD_SA_EMAIL }}
      GCP_PROJECT_ID_S: ${{ secrets.GCP_PROJECT_ID }}
      TFSTATE_BUCKET_S: ${{ secrets.TFSTATE_BUCKET }}
      TF_VARS_S: ${{ secrets.TF_VARS }}